function fcsvwrite(filename, fiducials, label)

filename = forceExtension(filename, '.fcsv');

fiducials = checkMeshDimension(fiducials, 2); % Nx3
numFiducials = size(fiducials, 1);

fid = fopen(filename, 'w');

fprintf(fid, '# Markups fiducial file version = 4.4\n');
fprintf(fid, '# CoordinateSystem = 0\n');
keys = {'# columns = id',...
          'x', ...
          'y', ...
          'z', ...
          'ow', ...
          'ox', ...
          'oy', ...
          'oz', ...
          'vis', ...
          'sel', ...
          'lock', ...
          'label', ...
          'desc', ...	
          'associatedNodeID'};
fieldsString = mystrjoin(keys, ',');
fprintf(fid, [fieldsString '\n']);

for i = 1:numFiducials
    fiducial = fiducials(i, :);
    valuesString = sprintf(['vtkMRMLMarkupsFiducialNode_%d,', ...
                      '%f,', ...
                      '%f,', ...
                      '%f,', ...
                      '0,0,0,1,1,0,1,', ...
                      '%s-%d\n'], ...
                      i-1, ...
                      fiducial(1), fiducial(2), fiducial(3), ...
                      label, i);
    fprintf(fid, valuesString);
end

fclose(fid);